server:
  port: 8080

spring:
  application:
    name: app-gateway

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/agw
    username: example_user
    password: example_password

  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.company.agw
  configuration:
    map-underscore-to-camel-case: true

external:
  kisa:
    base-url: https://example-kisa-api
  mmsc:
    base-url: https://example-mmsc-api
  rcs:
    base-url: https://example-rcs-api

logging:
  level:
    root: INFO
    com.company.agw: DEBUG
