driver=org.mariadb.jdbc.Driver
url=jdbc:mariadb:sequential//210.217.178.231:5500/aisfm
username=aisfm
password=
initialSize=10
minIdle=10
maxActive=200
maxIdle=50
maxWait=6000
testOnBorrow=true
testOnReturn=false
testWhileIdle=false
timeBetweenEvictionRunsMillis=-1
minEvictableIdleTimeMillis=120000
numTestsPerEvictionRun=5
removeAbandonedTimeout=30
removeAbandoned=false
logAbandoned=false

# VMHistoryDbDAO (sqlSessionTemplate2 / dataSource2)
history_driver=org.mariadb.jdbc.Driver
history_url=jdbc:mariadb:sequential//210.217.178.231:5500/aisfm
history_username=aisfm
history_password=aisfm12#$


history_initialSize=10
history_minIdle=10
history_maxActive=200
history_maxIdle=50

history_maxWait=6000
history_testOnBorrow=true
history_testOnReturn=false
history_testWhileIdle=false
history_timeBetweenEvictionRunsMillis=-1
history_minEvictableIdleTimeMillis=120000
history_numTestsPerEvictionRun=5
history_removeAbandonedTimeout=30
history_removeAbandoned=false
history_logAbandoned=false
